### PR TITLE
Fix Build Error

### PR DESCRIPTION
**Pull request by 0xA1n50ph**
This change fix the following error:

```
> Task :react-native-bluetooth-escpos-printer:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-bluetooth-escpos-printer:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/igorpires/Documents/Development/ArchitectureDesign/deltalog.ui/node_modules/react-native-bluetooth-escpos-printer/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/igorpires/Documents/Development/ArchitectureDesign/deltalog.ui/node_modules/react-native-bluetooth-escpos-printer/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/igorpires/Documents/Development/ArchitectureDesign/deltalog.ui/node_modules/react-native-bluetooth-escpos-printer/android/build/intermediates/res/merged/release/values/values.xml:2720: error: resource android:attr/fontVariationSettings not found.
  /Users/igorpires/Documents/Development/ArchitectureDesign/deltalog.ui/node_modules/react-native-bluetooth-escpos-printer/android/build/intermediates/res/merged/release/values/values.xml:2721: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
```

### CODE REVIEW

**Review by nowarzz — COMMENTED** [review]
It works

**Comment by vishaletm** [comment]
It works

**Comment by adyfk** [comment]
i still get an error

**Comment by michaelVictoriaDev** [comment]
how to fix this ?

**Comment by Joshmatjjen** [comment]
Still get an Error

**Comment by amirulasrof** [comment]
+1

**Pull request merged**
